// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUzR6hH-DtbnYf2-fADQNdIa77g8KZbVM',
    appId: '1:277150463102:web:df559845cdc2170731d42f',
    messagingSenderId: '277150463102',
    projectId: 'quantro-money-manager',
    authDomain: 'quantro-money-manager.firebaseapp.com',
    storageBucket: 'quantro-money-manager.firebasestorage.app',
    measurementId: 'G-QFM43CQK3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbixOc6qSv9R43bbVa3t52rQvE6wqI6uw',
    appId: '1:277150463102:android:4540fe0bf9933dbf31d42f',
    messagingSenderId: '277150463102',
    projectId: 'quantro-money-manager',
    storageBucket: 'quantro-money-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5Oqh8VdMqA2YVH_CkyS61O4ZkuMr3FLc',
    appId: '1:277150463102:ios:223d9503799ea7b731d42f',
    messagingSenderId: '277150463102',
    projectId: 'quantro-money-manager',
    storageBucket: 'quantro-money-manager.firebasestorage.app',
    iosClientId: '277150463102-medk276ai2ebs565gauce15a54kbm2r8.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5Oqh8VdMqA2YVH_CkyS61O4ZkuMr3FLc',
    appId: '1:277150463102:ios:223d9503799ea7b731d42f',
    messagingSenderId: '277150463102',
    projectId: 'quantro-money-manager',
    storageBucket: 'quantro-money-manager.firebasestorage.app',
    iosClientId: '277150463102-medk276ai2ebs565gauce15a54kbm2r8.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUzR6hH-DtbnYf2-fADQNdIa77g8KZbVM',
    appId: '1:277150463102:web:a0d45158648ab2f231d42f',
    messagingSenderId: '277150463102',
    projectId: 'quantro-money-manager',
    authDomain: 'quantro-money-manager.firebaseapp.com',
    storageBucket: 'quantro-money-manager.firebasestorage.app',
    measurementId: 'G-DFTENLHZ9Z',
  );
}
